config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root 'static_pages#home'
  resources :projects do 
    resources :bugs, except: [:index, :show]
    resources :team_memberships, only: [:new, :create, :destroy]
  end
  
  patch "bug/:id", to: "bugs#update_solved_status", as: "update_bug_solved_status"
  
  resources :comments, only: [:create]
  
  get "become_user/:id", to: "application#become_user", as: "become_user"
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  
  belongs_to :user
  has_many :bugs, dependent: :destroy
  
  has_many :team_memberships, dependent: :destroy
  has_many :allowed_users, through: :team_memberships, source: :user
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :allow_only_owner, only: [:edit, :update, :destroy]
  before_action :allow_only_team, only: [:show]
  

  def index
    @projects = Project.where(user: current_user) + current_user.allowed_projects
  end
  
  def show
    @project = Project.find(params[:id])
    @project_solved_bugs = @project.bugs.where(solved: true).order(:id).includes(:user, :comments)
    @project_unsolved_bugs = @project.bugs.where(solved: false).order(:id).includes(:user, :comments)
    @comment = Comment.new
  end
  
  def new
    @project = Project.new
  end
  
  def edit 
    @project = Project.find(params[:id])
  end
  
  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:success] = "You created the project: #{@project.name}"
      redirect_to projects_path
    else 
      flash.now[:error] = "There was an error while creating the project."
      render :new
    end
  end
  
  def update 
    @project = Project.find(params[:id])
    if @project.update_attributes(project_params)
      flash[:success] = "Project updated."
      redirect_to projects_path
    else 
      flash.now[:error] = "There was an error while updating the project."
      render :edit
    end
  end
  
  def destroy 
    @project = Project.find(params[:id])
    if @project.destroy
      flash[:success] = "Project #{@project.name} deleted"
      redirect_to projects_url 
    else 
      flash[:error] = "There was an error while deleting the project."
      redirect_to projects_url
    end
  end
  
  private
  
    def project_params
      params.require(:project).permit(:name, :description).merge(user: current_user)
    end
    
    def allow_only_owner
      @project = Project.find(params[:id])
      redirect_to root_url if current_user.id != @project.user_id
    end
    
    def allow_only_team
      @project = Project.find(params[:id])
      allowed_team_ids = @project.allowed_user_ids << @project.user_id
      if !allowed_team_ids.include?(current_user.id)
        flash[:error] = "You're not allowed to access this project."
        redirect_to root_url 
      end
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  
  def project_ownership(project)
    # if current user owns the project
    if project.user_id == current_user.id
      if current_page?(projects_path)
        @data = "<p class='project-owner'>You created this project.</p>" 
      else
        index_link = link_to("the project index page", projects_path)
        
        @data = "<div class='project-ownership'>
                  <p>You created this project.</p>
                  
                  <span>You can:</span>
                  <ul>
                    <li>Manage the team</li>
                    <li>Report bugs</li>
                    <li>Mark as solved / edit / delete all the bugs</li>
                    <li>Comment on bugs</li>
                    <li>Edit or delete the project via #{index_link}</li>
                  </ul>
                </div>"
      end
      @data.html_safe
    # if current user doesn't own the project
    else 
      if current_page?(projects_path)
        @data = "<p class='project-owner'>
                   #{project.user.username} created this project.
                   You are part of this project team.
                 </p>" 
      else
        @data = "<div class='project-ownership'>
                  <p>
                    #{project.user.username} created this project.
                    You are part of this project team.
                  </p>
                  
                  <span>You can:</span>
                  <ul>
                    <li>Report bugs</li>
                    <li>Mark as solved / edit / delete your own bugs</li>
                    <li>Comment on all bugs</li>
                  </ul>
                  <p>
                    If you wish to manage the team or all the bugs of the project,
                    you need to #{ link_to "Login as owner",
                                            become_user_path(project.user.id),
                                            class: 'btn btn-sm btn-success' }
                  </p>
                </div>"
      end
      @data.html_safe
    end
  end
end

app/views/projects/_project_card.html.erb
<div class="card border-primary project-card">
  <%= link_to project_path(project), id: "project-#{project.name}" do %> 
    <div class="card-header">
      <h4 class="project-card-title">
        <%= project.name  %>
      </h4>
    </div>
  <% end %>
  <div class="card-body">
    <p class="card-text">
      <%= project.description %>
    </p>
    
    <%= project_ownership(project) %>
    
  </div>
  <div class="card-footer">
    <%= link_to "Show", project_path(project), class: "btn btn-primary" %>
    
    <% if current_user.id == project.user.id %>
    <%= link_to "Edit", edit_project_path(project), class: "btn btn-info" %>
    <%= link_to "Delete", project_path(project), method: :delete,
                          id: "delete-project-#{project.id}",
                          class: "btn btn-danger" %>
    <% end %>
  </div>
</div>

app/views/projects/_project_team_member.html.erb
<li class="list-group-item d-flex justify-content-between align-items-center">
  <%= membership.user.username %> - <%= membership.user.email %>
  
  <!-- Only project owner can see the remove user button -->
  <% if current_user.id == @project.user_id %>
    <%= link_to "remove", project_team_membership_path(@project, membership),
                          class: "btn btn-sm btn-danger", 
                          method: :delete,
                          confirm: "Are you sure?" %>
  <% end %>
</li>

app/views/projects/edit.html.erb
<div class="row">
  <div class="col-md-8 offset-md-2">
    <h1 class="top-page-title" align="center">Edit project</h1>
    <%= form_with model: @project, local: true, html: { class: "needs-validation", novalidate: true } do |f| %>
      
      <div class="form-group">
        <%= f.label :name  %>
        <%= f.text_field :name, class: "form-control", required: true %>
        <%= render "shared/new_form_validations" %>
      </div>
      
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control", required: true %>
        <%= render "shared/new_form_validations" %>
      </div>
      
      <div class="form-group">
        <%= f.submit "Save changes", class: "btn btn-success"%>
      </div>
    <% end %>
  </div>
</div>


<%= javascript_include_tag "bootstrap_form_validations" %>

app/views/projects/index.html.erb
<div class="row">
  <div class="col-md-8 offset-md-2">
    <h1 class="top-page-title" align="center">My projects</h1>
    
    <%= render partial: "project_card", collection: @projects, as: :project %>
  </div>
</div>

app/views/projects/new.html.erb
<div class="row">
  <div class="col-md-8 offset-md-2">
    <h1 class="top-page-title" align="center">New project</h1>
    <%= form_with model: @project, local: true, html: { class: "needs-validation", novalidate: true } do |f| %>
      
      <div class="form-group">
        <%= f.label :name  %>
        <%= f.text_field :name, class: "form-control", required: true %>
        <%= render "shared/new_form_validations" %>
      </div>
      
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control", required: true %>
        <%= render "shared/new_form_validations" %>
      </div>
      
      <div class="form-group">
        <%= f.submit "Create", class: "btn btn-success"%>
      </div>
    <% end %>
  </div>
</div>

<%= javascript_include_tag "bootstrap_form_validations" %>

app/views/projects/show.html.erb
<div class="row">
  <div class="col-md-8 offset-md-2">
    <h1 class="top-page-title" align="center"><%= @project.name %></h1>
    
    <h2>Description</h2>
    <p class="project-description">
      <%= @project.description %>
    </p>
    <%= project_ownership(@project) %>
    
    <!-- Team -->
    <div class="row no-gutters align-items-center justify-content-between">
      <h2 class="col-4">Team</h2>
      
      <!-- Only project owner can see the Add user button -->
      <% if current_user.id == @project.user_id %>
        <%= link_to "Add user", new_project_team_membership_path(@project),
                                class: "btn btn-primary" %>
      <% end %>
    </div>
    
    <div id="project-team-list">
      <p>
        These users have access to this project: <br/>
        (They can report bugs and comment)
      </p>
        <ul class="list-group" id="team-user-list">
          <%= render partial: "team_memberships/team_member", 
                     collection: @project.team_memberships, 
                     as: :membership,
                     locals: { project: @project } %>
        </ul>
    </div>
        
    <!-- Bugs -->
    <div class="row no-gutters align-items-center justify-content-between">
      <h2 class="col-4">Bugs</h2>
      <%= link_to "Report Bug", new_project_bug_path(@project), class: "btn btn-primary" %>
    </div>
    
    <p class="bugs-instructions">Click on a bug for more infos.</p>
    
    <% if !@project.bugs.empty? %>
      <h4 class="solved-status-title">Unsolved</h4>
      
      <div id="accordion">
        <%= render partial: "bugs/bug", collection: @project_unsolved_bugs, as: :bug,
                                        locals: { project: @project, comment: @comment } %>
      </div>
      
      <h4 id="solved-bugs-title" class="solved-status-title">Solved</h4>
      
      <div id="accordion">
        <%= render partial: "bugs/bug", collection: @project_solved_bugs, as: :bug,
                                        locals: { project: @project, comment: @comment } %>
      </div>
    <% end %>
  </div>
</div>