config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root 'static_pages#home'
  resources :projects do 
    resources :bugs, except: [:index, :show]
    resources :team_memberships, only: [:new, :create, :destroy]
  end
  
  patch "bug/:id", to: "bugs#update_solved_status", as: "update_bug_solved_status"
  
  resources :comments, only: [:create]
  
  get "become_user/:id", to: "application#become_user", as: "become_user"
end

app/models/bug.rb
class Bug < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  
  belongs_to :project
  belongs_to :user
  
  has_many :comments, -> { includes(:user) }, dependent: :destroy
  
  def mark_as_solved
    self.update_attributes(solved: true)
  end
  
  def mark_as_unsolved
    self.update_attributes(solved: false)
  end
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :allow_only_team, only: [:new, :create]
  before_action :allow_only_owners, only: [:edit, :update, :destroy, :update_solved_status]
  
  def new
    @project = Project.find(params[:project_id])
    @bug = @project.bugs.build
  end
  
  def edit
    @project = Project.find(params[:project_id])
    @bug = @project.bugs.find(params[:id])
  end
  
  def create
    @project = Project.find(params[:project_id])
    @bug = @project.bugs.build(bug_params.merge(user: current_user))
    if @bug.save
      flash[:success] = "Bug reported."
      redirect_to project_path(@bug.project)
    else 
      flash.now[:error] = "There was an error while creating the bug."
      render :new
    end
  end
  
  def update
    @project = Project.find(params[:project_id])
    @bug = @project.bugs.find(params[:id])
    if @bug.update_attributes(bug_params)
      flash[:success] = "Bug updated."
      redirect_to project_path(@project)
    else 
      flash.now[:error] = "There was an error while updating the bug."
      render :edit
    end
  end
  
  def destroy
    @project = Project.find(params[:project_id])
    @bug = @project.bugs.find(params[:id])
    if @bug.destroy
      flash[:success] = "Bug deleted."
      redirect_to project_path(@project)
    else 
      flash[:error] = "There was an error while deleting the bug."
      redirect_to project_path(@project)
    end
  end
  
  def update_solved_status
    @bug = Bug.find(params[:id])
    if @bug.solved?
      @bug.mark_as_unsolved
      flash[:success] = "Bug marked as unsolved."
      redirect_to project_path(@bug.project)
    else 
      @bug.mark_as_solved
      flash[:success] = "Bug marked as solved."
      redirect_to project_path(@bug.project)
    end
  end
  
  private
  
    def bug_params
      params.require(:bug).permit(:name, :description)
    end
    
    def allow_only_team
      @project = Project.find(params[:project_id])
      allowed_team_ids = @project.allowed_user_ids << @project.user_id
      if !allowed_team_ids.include?(current_user.id)
        flash[:error] = "You're not allowed to access this project."
        redirect_to root_url 
      end
    end
    
    def allow_only_owners
      if params[:project_id]
        @project = Project.find(params[:project_id])
        @bug = @project.bugs.find(params[:id])
      else 
        @bug = Bug.find(params[:id])
        @project = @bug.project
      end
      
      if current_user.id != @project.user_id && current_user.id != @bug.user_id
        flash[:error] = "You're not allowed to access this bug."
        redirect_to root_url
      end
    end
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/views/bugs/_bug.html.erb
<div class="card">
  <div class="card-header" id="heading<%= bug.id %>">
    <h5 class="mb-0 bug-card-title">
      <button class="btn btn-link collapse-button" data-toggle="collapse"
              data-target="#collapse<%= bug.id %>" aria-expanded="true" 
              aria-controls="collapse<%= bug.id %>">
        
        <%= bug.name %> - reported by <%= bug.user.username %>
      </button>
    </h5>
    
    <!-- Only project owner or bug creator have access to bug actions -->
    <% if current_user.id == project.user_id || current_user.id == bug.user_id %>
      <%= render partial: "bugs/bug_card_actions", locals: { bug: bug, project: project } %>
    <% end %>
  </div>

  <div id="collapse<%= bug.id %>" class="collapse" aria-labelledby="heading<%= bug.id %>" data-parent="#accordion">
    <div class="card-body bug-card-body">
      <h5>Description:</h5>
      
      <p class="bug-description">
        <%= bug.description %>
        <br />
        -- reported by: <%= bug.user.username %>
      </p>
      
      <!-- Comments -->
      <h5 class="comments-title">Comments:</h5>
      
      <div class="bug-comments" id="bug-<%= bug.id %>-comments">
        <!-- Uses partial _comment -->
        <%= render bug.comments %>
      </div>
      
      <%= render partial: "comments/comment_form", locals: { bug: bug, 
                                                             comment: comment,
                                                             project: project } %>
      
    </div>
  </div>
</div>

app/views/bugs/_bug_card_actions.html.erb
<span class="bug-card-actions">
  <% if bug.solved? %> 
    <%= link_to "Mark as unsolved",
                update_bug_solved_status_path(bug),
                method: :patch,
                id: "update-bug-solved-#{bug.id}",
                class: "btn-sm btn-warning" %>
  <% else %> 
    <%= link_to "Mark as solved",
                update_bug_solved_status_path(bug),
                method: :patch,
                id: "update-bug-solved-#{bug.id}",
                class: "btn-sm btn-success" %>
  <% end %>

  <%= link_to "Edit", edit_project_bug_path(project, bug),
                      class: "btn-sm btn-info" %>
  <%= link_to "Delete", project_bug_path(project, bug),
                        method: :delete,
                        id: "delete-bug-#{bug.id}",
                        class: "btn-sm btn-danger", 
                        data: { confirm: "Are you sure?" } %>
</span>

app/views/bugs/edit.html.erb
<div class="row">
  <div class="col-md-8 offset-md-2">
    <h1 class="top-page-title" align="center">Edit bug</h1>
    <%= form_with model: [@project, @bug], local: true, html: { class: "needs-validation", novalidate: true } do |f| %>
      <legend>From project: <%= @project.name %></legend>
      
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control", required: true %>
        <%= render "shared/new_form_validations" %>
      </div>
      
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control", required: true %>
        <%= render "shared/new_form_validations" %>
      </div>
      
      <div class="form-group">
        <%= f.submit "Save changes", class: "btn btn-success"%>
      </div>
    <% end %>
  </div>
</div>

<%= javascript_include_tag "bootstrap_form_validations" %>

app/views/bugs/new.html.erb
<div class="row">
  <div class="col-md-8 offset-md-2">
    <h1 class="top-page-title" align="center">Report bug</h1>
    <%= form_with model: [@project, @bug], local: true, html: { class: "needs-validation", novalidate: true } do |f| %>
      <legend>Report a bug on project: <%= @project.name %></legend>
      
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control", required: true %>
        <%= render "shared/new_form_validations" %>
      </div>
      
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control", required: true %>
        <%= render "shared/new_form_validations" %>
      </div>
      
      <div class="form-group">
        <%= f.submit "Report", class: "btn btn-success"%>
      </div>
    <% end %>
  </div>
</div>


<%= javascript_include_tag "bootstrap_form_validations" %>