config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root 'static_pages#home'
  resources :projects do 
    resources :bugs, except: [:index, :show]
    resources :team_memberships, only: [:new, :create, :destroy]
  end
  
  patch "bug/:id", to: "bugs#update_solved_status", as: "update_bug_solved_status"
  
  resources :comments, only: [:create]
  
  get "become_user/:id", to: "application#become_user", as: "become_user"
end

app/models/team_membership.rb
class TeamMembership < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/controllers/team_memberships_controller.rb
class TeamMembershipsController < ApplicationController
  
  before_action :allow_only_owner, only: [:new, :create, :destroy]
  
  def new
    @project = Project.find(params[:project_id])
    @users = User.select { |user| user.id != current_user.id && !@project.allowed_user_ids.include?(user.id) }
  end
  
  def create
    @project = Project.find(params[:project_id])
    @user = User.find(params[:user_id])
    @membership = @project.team_memberships.build(user: @user)
    if @membership.save
      flash[:success] = "#{@user.username} was added to this project team."
      redirect_to project_url(@project)
    else 
      flash.now[:error] = "There was an error while adding this user to the project team."
      render :new
    end
  end
  
  def destroy
    @team_membership = TeamMembership.find(params[:id])
    if @team_membership.delete
      flash[:success] = "#{@team_membership.user.username} was removed from this project team."
      redirect_to project_path(@team_membership.project)
    else 
      flash[:error] = "There was an error while removing this user from the project team."
      redirect_to project_path(@team_membership.project)
    end
  end
  
  private 
  
    def allow_only_owner
      @project = Project.find(params[:project_id]) || TeamMembership.find(params[:id]).project
      redirect_to root_url if current_user.id != @project.user_id
    end
end

app/helpers/team_memberships_helper.rb
module TeamMembershipsHelper
end

app/views/team_memberships/_team_member.html.erb
<li class="list-group-item d-flex justify-content-between align-items-center">
  <%= membership.user.username %> - <%= membership.user.email %>
  
  <div class="team-actions">
    <!-- Login as links are available for everybody -->
    <% if current_user.id != membership.user.id %>
      <%= link_to "Login as", become_user_path(membership.user.id),
                               class: "btn btn-sm btn-success" %>
    <% else %>
      <span>(You)</span>
    <% end %>
    <!-- Only project owner can see the remove user button -->
    <% if current_user.id == project.user_id %>
      <%= link_to "remove", project_team_membership_path(project, membership),
                            class: "btn btn-sm btn-danger", 
                            method: :delete,
                            confirm: "Are you sure?" %>
    <% end %>
  </div>
</li>

app/views/team_memberships/new.html.erb
<div class="row">
  <div class="col-md-8 offset-md-2">
    <h1 class="top-page-title" align="center">Add user</h1>
    <h4>Add a user to project: <%= @project.name %></h4>
    <br/>
    <h4>List of users</h4>
    
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Username</th>
          <!--<th scope="col">Email</th>-->
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.username %></th>
            <!--<td><%#= user.email %></td>-->
            <td>
              <%= link_to "Add", project_team_memberships_path(@project, user_id: user.id),
                                  method: :post, class: "btn btn-sm btn-success"  %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table> 
  </div>
</div>