config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root 'static_pages#home'
  resources :projects do 
    resources :bugs, except: [:index, :show]
    resources :team_memberships, only: [:new, :create, :destroy]
  end
  
  patch "bug/:id", to: "bugs#update_solved_status", as: "update_bug_solved_status"
  
  resources :comments, only: [:create]
  
  get "become_user/:id", to: "application#become_user", as: "become_user"
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <%= link_to "BugTracker", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item <%= 'active' if current_page?(root_path) %>">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      
      <!-- only logged in user can see projects#index and projects#new -->
      <% if user_signed_in? %>
        <li class="nav-item <%= 'active' if current_page?(projects_path) %>">
          <%= link_to "My Projects", projects_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(new_project_path) %>">
          <%= link_to "New project", new_project_path, class: "nav-link" %>
        </li>
      <% end %>
      
      <li class="nav-item">
        <% if user_signed_in? %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link logout-link" %>
        <% else %>
          <%= link_to "Login", new_user_session_path, class: "nav-link login-link" %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BugTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- Required Bootstrap meta tag -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, minimum-scale=1">
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <!-- flash message display -->
    <% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= value %>
      </div>
    <% end %>
    <!---->
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>